# 1.  A F&B manager wants to determine whether there is any significant difference in the diameter of the cutlet between two units. A randomly selected sample of cutlets was collected from both units and measured? Analyze the data and draw inferences at 5% significance level. Please state the assumptions and tests that you carried out to check validity of the assumptions.


In [36]:
import pandas as pd
import numpy as np
from scipy import stats
from scipy.stats import norm

In [5]:
# Load the dataset
data=pd.read_csv('Cutlets.csv')
data.head()

Unit A  Unit B
0  6.8090  6.7703
1  6.4376  7.5093
2  6.9157  6.7300
3  7.3012  6.7878
4  7.4488  7.1522

In [6]:
data.describe()


Unit A     Unit B
count  35.000000  35.000000
mean    7.019091   6.964297
std     0.288408   0.343401
min     6.437600   6.038000
25%     6.831500   6.753600
50%     6.943800   6.939900
75%     7.280550   7.195000
max     7.516900   7.545900

In [35]:
#Assumptions: H0: mu(unit A) = mu(unit B) - No significant difference in the diameter of the cutlet between two units H1: mu(Unit A) != mu(Unit B) - There's significant difference in the diameter of the cutlet between two unitsWe have two samples hence Two tail test will be applicable here.

In [7]:
unitA=pd.Series(data.iloc[:,0])
unitA

0     6.8090
1     6.4376
2     6.9157
3     7.3012
4     7.4488
5     7.3871
6     6.8755
7     7.0621
8     6.6840
9     6.8236
10    7.3930
11    7.5169
12    6.9246
13    6.9256
14    6.5797
15    6.8394
16    6.5970
17    7.2705
18    7.2828
19    7.3495
20    6.9438
21    7.1560
22    6.5341
23    7.2854
24    6.9952
25    6.8568
26    7.2163
27    6.6801
28    6.9431
29    7.0852
30    6.7794
31    7.2783
32    7.1561
33    7.3943
34    6.9405
Name: Unit A, dtype: float64

In [8]:
unitB=pd.Series(data.iloc[:,1])
unitB

0     6.7703
1     7.5093
2     6.7300
3     6.7878
4     7.1522
5     6.8110
6     7.2212
7     6.6606
8     7.2402
9     7.0503
10    6.8810
11    7.4059
12    6.7652
13    6.0380
14    7.1581
15    7.0240
16    6.6672
17    7.4314
18    7.3070
19    6.7478
20    6.8889
21    7.4220
22    6.5217
23    7.1688
24    6.7594
25    6.9399
26    7.0133
27    6.9182
28    6.3346
29    7.5459
30    7.0992
31    7.1180
32    6.6965
33    6.5780
34    7.3875
Name: Unit B, dtype: float64

In [9]:
# 2-sample 2-tail ttest:   stats.ttest_ind(array1,array2)     # ind -> independent samples
p_value=stats.ttest_ind(unitA,unitB)
p_value

Ttest_indResult(statistic=0.7228688704678063, pvalue=0.4722394724599501)

In [10]:
p_value[1]     # 2-tail probability 


0.4722394724599501

In [ ]:
#Here, pvalue=0.4722394724599501. Since pvalue > (α = 0.05), accept Null Hypothesis (H0), and reject Alternative Hypothesis (H1).
#Inference: There's No significant difference in the diameter of the cutlet between two units
#OR compare p_value with α = 0.05 (At 5% significance level) As (p_value=0.4722) > (α = 0.05); Accept Null Hypothesis i.e. μ1 = μ2
#Inference: there is no difference in diameters of cutlets between two units)

# 2. A hospital wants to determine whether there is any difference in the average Turn Around Time (TAT) of reports of the laboratories on their preferred list. They collected a random sample and recorded TAT for reports of 4 laboratories. TAT is defined as sample collected to report dispatch.
   
  #Analyze the data and determine whether there is any difference in average TAT among the different laboratories at 5% significance level.


In [11]:
import pandas as pd
import numpy as np
from scipy import stats
from scipy.stats import norm

In [12]:
# load the dataset
Lab=pd.read_csv('LabTAT.csv')
Lab.head()

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0        185.35        165.53        176.70        166.13
1        170.49        185.91        198.45        160.79
2        192.77        194.92        201.23        185.18
3        177.33        183.00        199.61        176.42
4        193.41        169.57        204.63        152.60

In [38]:
#Assumptions: H0: mu(Laboratory 1) = mu(Laboratory 2) = mu(Laboratory 3) = mu(Laboratory 4) i.e. there is no difference in the average Turn Around Time (TAT) of reports of the 4 - laboratories H1: At least one of average TAT is not equal to other three. i.e. there is some difference in the average Turn Around Time (TAT) of reports of the 4 - laboratories Here, we got a data for 4 different laboratories and we are analyzing the outcomes based on only one factor i.e. Average Turn Around Time (TAT), hence oneway ANOVA test will be applicable for this problem statement.

In [14]:
# Anova ftest statistics: stats.f_oneway(column-1,column-2,column-3,column-4)
p_value=stats.f_oneway(Lab.iloc[:,0],Lab.iloc[:,1],Lab.iloc[:,2],Lab.iloc[:,3])
p_value

F_onewayResult(statistic=118.70421654401437, pvalue=2.1156708949992414e-57)

In [16]:
p_value[1] # compare it with α = 0.05

2.1156708949992414e-57

In [42]:
#Here, pvalue=2.1156708949992414e-57 which is much higher than (α = 0.05). Hence we will accept Null Hypothesis (H0) and reject alternate hypothesis (H1).
#Inference: H0: There is no difference in the average Turn Around Time (TAT) of reports of the 4 - laboratories
#OR compare p_value with α = 0.05 As (p-value=0) > (α = 0.05); Accept Null Hypothesis i.e.,No difference in the average Turn Around Time
#Inference: H0: mu(Laboratory 1) = mu(Laboratory 2) = mu(Laboratory 3) = mu(Laboratory 4) i.e. there is no difference in the average Turn Around Time (TAT) of reports of the 4 - laboratories

# 3. Sales of products in four different regions is tabulated for males and females. Find if male-female buyer rations are similar across regions.

In [29]:
from scipy.stats import chi2_contingency


In [30]:
BuyerRatio =pd.read_csv('BuyerRatio.csv')
BuyerRatio.head()

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [31]:
BuyerRatio.describe()


East         West        North       South
count    2.000000     2.000000     2.000000    2.000000
mean   242.500000   832.500000   743.500000  410.000000
std    272.236111   976.514465   866.205807  480.832611
min     50.000000   142.000000   131.000000   70.000000
25%    146.250000   487.250000   437.250000  240.000000
50%    242.500000   832.500000   743.500000  410.000000
75%    338.750000  1177.750000  1049.750000  580.000000
max    435.000000  1523.000000  1356.000000  750.000000

In [34]:
#Hypothesis: H0: Male-female buyer rations are similar across regions. H1: Male-female buyer rations are not similar across regions.


In [32]:
obs=np.array([[50,142,131,70],[435,1523,1356,750]])
obs

array([[  50,  142,  131,   70],
       [ 435, 1523, 1356,  750]])

In [33]:
chi2_contingency(obs)


(1.595945538661058,
 0.6603094907091882,
 3,
 array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
        [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

In [43]:
#Here, p_value = 0.6603094907091882Since, p_Value(0.66030949) > aplha(0.05), We will accept null hypothesis.
#Inference: Male-female buyer rations are similar across regions.
#or Compare p_value with α = 0.05 As (p-value = 0.6603) > (α = 0.05); Accept the Null Hypothesis i.e. Independence of categorical variables.
#Inference: male-female buyer rations are similar across regions and are not related

# 4. TeleCall uses 4 centers around the globe to process customer order forms. They audit a certain %  of the customer order forms. Any error in order form renders it defective and has to be reworked before processing.  The manager wants to check whether the defective %  varies by centre. Please analyze the data at 5% significance level and help the manager draw appropriate inferences


In [17]:
import pandas as pd
import numpy as np
from scipy import stats
from scipy.stats import norm
from scipy.stats import chi2_contingency

In [19]:
data1=pd.read_csv('Costomer+OrderForm.csv')
data1

Phillippines   Indonesia       Malta       India
0     Error Free  Error Free   Defective  Error Free
1     Error Free  Error Free  Error Free   Defective
2     Error Free   Defective   Defective  Error Free
3     Error Free  Error Free  Error Free  Error Free
4     Error Free  Error Free   Defective  Error Free
..           ...         ...         ...         ...
295   Error Free  Error Free  Error Free  Error Free
296   Error Free  Error Free  Error Free  Error Free
297   Error Free  Error Free   Defective  Error Free
298   Error Free  Error Free  Error Free  Error Free
299   Error Free   Defective   Defective  Error Free

[300 rows x 4 columns]

In [40]:
#Hypothesis: H0: Proportion of defective % across the center is same. H1: Proportion of defective % across the center is different.


In [20]:
data1.Phillippines.value_counts()


Error Free    271
Defective      29
Name: Phillippines, dtype: int64

In [21]:
data1.Indonesia.value_counts()


Error Free    267
Defective      33
Name: Indonesia, dtype: int64

In [22]:
data1.Malta.value_counts()


Error Free    269
Defective      31
Name: Malta, dtype: int64

In [23]:
data1.India.value_counts()


Error Free    280
Defective      20
Name: India, dtype: int64

In [24]:
# Make a contingency table
obs=np.array([[271,267,269,280],[29,33,31,20]])
obs

array([[271, 267, 269, 280],
       [ 29,  33,  31,  20]])

In [25]:
# Chi2 contengency independence test
chi2_contingency(obs) # o/p is (Chi2 stats value, p_value, df, expected obsvations)

(3.858960685820355,
 0.2771020991233135,
 3,
 array([[271.75, 271.75, 271.75, 271.75],
        [ 28.25,  28.25,  28.25,  28.25]]))

In [41]:
#Here, p_value = 0.2771020991233135 Since p_value(0.2771020991233135) > alpha(0.05), Accept null hypothesis.
#Inference: Proportion of defective % across the center is same.
#OR Compare p_value with α = 0.05 As (p_value = 0.2771) > (α = 0.05); Accept Null Hypthesis i.e. Independence of categorical variables,
#Inference: customer order forms defective % does not varies by centre